### ISSUE TITLE
Flexbox, Bootstrap eller Semantic

### ISSUE THREAD

**Issue by baraabd** [baraabd/TechStore-Grupp1#15]
Vilken tekniker ska vi använd?

**Comment by afshar20922019** [comment]
Jag tror flex box är bättre och lättare.

**Comment by anukhatra** [comment]
Jag tror att vi kan använd grid ,eller hur?

**Comment by baraabd** [comment]
Okej! Ska vi använda Flexbox ochGrid teknik. stämmer
