### ISSUE TITLE
Add product to localstorage

### ISSUE THREAD

**Issue by anukhatra** [baraabd/TechStore-Grupp1#21]
Adding product i.e. list of product to the local storage.

**Comment by afshar20922019** [comment]
![Add product to localstorage](https://user-images.githubusercontent.com/55985278/67273761-60b64680-f4bf-11e9-9a3e-af3e82f447ee.jpg)

**Comment by afshar20922019** [comment]
![10-22-2019 11-31-37](https://user-images.githubusercontent.com/55985278/67273844-88a5aa00-f4bf-11e9-9202-414e8f99a493.jpg)

**Comment by afshar20922019** [comment]
localStorage.setItem('listOfProducts', JSON.stringify(listOfProducts));
