### ISSUE TITLE
Design navigation bar

### ISSUE THREAD

**Issue by baraabd** [baraabd/TechStore-Grupp1#8]
![Header](https://user-images.githubusercontent.com/55985500/66188464-9669cb80-e687-11e9-9d62-ea68c38031f8.jpg)

**Design navigation på två sidor: Start View och Shopping kart**

Hemsidan skall innehålla en fixerad navigationsbar längst upp på sidan som går hela vägen från vänster till höger.
Till vänster i navigationsbaren skall det finnas en titel (TechStore) som skall vara klickbar, ett klick på titeln tar användaren till startsidan.
Till höger i navigationsbaren skall det finnas en kundvagnsknapp som skall vara klickbar, ett klick på knappen tar användaren till kundvagnssidan.
När en produkt läggs till i kundvagnen skall detta reflekteras med att det visas en siffra intill kundvagnsknappen som reflekterar antalet produkter i kundvagnen.

**Comment by afshar20922019** [comment]
<header id="myheader">
        <div class="logo">

            <h1>TechStore</h1>


        </div>
        <div class="shopping-cart">
            <i class="fas fa-shopping-cart"></i>
        </div>
    </header>

**Comment by afshar20922019** [comment]
Jag gjorde så här

**Comment by afshar20922019** [comment]
Man kan skapa header med JavaScript också
![10-4-2019 09-34-30](https://user-images.githubusercontent.com/55985278/66189537-3de7fd80-e68a-11e9-86c4-be0cf60b1b2d.jpg)

**Comment by afshar20922019** [comment]
Vad tror ni?????

**Comment by baraabd** [comment]
Hur den här kuden ser ut på projekt (Html)?

**Comment by anukhatra** [comment]
vi kan skriva header i html

**Comment by afshar20922019** [comment]
Perfekt!!!!!!!!!!!!!!1111

**Comment by baraabd** [comment]
Jag tror att använda html för att skappa header, det är änkelt.

Vad tror ni också?

**Comment by afshar20922019** [comment]
Absoluttttt

**Comment by afshar20922019** [comment]
![10-4-2019 09-45-57](https://user-images.githubusercontent.com/55985278/66190244-e3e83780-e68b-11e9-86c4-e8635aadb380.jpg)
![10-4-2019 09-46-14](https://user-images.githubusercontent.com/55985278/66190245-e3e83780-e68b-11e9-86c3-c3a18b4fa244.jpg)






Vad tror ni?????????+++

**Comment by afshar20922019** [comment]
![10-4-2019 09-47-40](https://user-images.githubusercontent.com/55985278/66190311-067a5080-e68c-11e9-9ec1-3d6da4303b1e.jpg)



**Länka fontawsome**

**Comment by afshar20922019** [comment]
ok?????

**Comment by afshar20922019** [comment]
Men den är inte fixerad ännu

**Comment by baraabd** [comment]
Bra jobbat! 

Kan du push koden på Fork program för att visa koden sen fattar vi beslut?

**Comment by afshar20922019** [comment]
Vi kan göra det på måndag tillsammans

**Comment by afshar20922019** [comment]
![header](https://user-images.githubusercontent.com/55985278/67274090-0ff31d80-f4c0-11e9-857c-0794e49b142c.jpg)


Jag tror den här är bra.

Vad tror ni?





 <header>
        <div class="logo">
            <h1>TechStore</h1>
        </div>
        <div class="shopping-cart">
            <i id="counter-shop" class="fas fa-shopping-cart"></i>
        </div>

    </header>

header {
    display: flex;
    background-color: black;
    min-height: 5em;
    justify-content: space-around;
    align-items: center;
    flex-wrap: wrap;
}

header h1 {
    color: white;
}

.shopping-cart {
    display: flex;
    font-size: 40px;
    color: white;
}
