### ISSUE TITLE
Design Products på Start view

### ISSUE THREAD

**Issue by baraabd** [baraabd/TechStore-Grupp1#9]
Startsidan skall lista produkterna som finns i products.json filen.
Varje presentationsyta för produkterna skall ta upp ungefär hela höjden av skärmen och presentera all produktinformation.
Det skall även, för varje produkt, finnas en knapp för att lägga till produkterna i kundvagnen.
Produkterna som har lags till i kundvagnen skall sparas i localStorage så det är möjligt att komma åt informationen från alla sidor.

![startview-desktop](https://user-images.githubusercontent.com/55985500/66188899-d2516080-e688-11e9-890f-d067a5106347.jpg)
![startview-mobile](https://user-images.githubusercontent.com/55985500/66188900-d2516080-e688-11e9-890b-dc8f076283a8.jpg)
![startview-tablet](https://user-images.githubusercontent.com/55985500/66188901-d2516080-e688-11e9-9d33-33518ae69461.jpg)

**Comment by afshar20922019** [comment]
En produkt på row or column??
![10-4-2019 09-39-41](https://user-images.githubusercontent.com/55985278/66189809-ea29e400-e68a-11e9-9766-6233f61c4f7b.jpg)

**Comment by baraabd** [comment]
En produkt en row bara.

https://user-images.githubusercontent.com/55985500/66188899-d2516080-e688-11e9-890f-d067a5106347.jpg

**Comment by afshar20922019** [comment]
Så här blir det:





![TechStore](https://user-images.githubusercontent.com/55985278/66255227-951cc980-e781-11e9-900f-f297621abb92.png)
